networks:
  default:
    name: settlewithcircles

services:
  django:
    image: django-docker
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "gunicorn","--bind","0.0.0.0:9000","project.wsgi:application","--chdir","/app","--workers","2" ]
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    restart: unless-stopped
  db:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - ./docker/.prebuilt.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - settlewithcircles-redis-data:/data
    ports:
      - "6380:6379"
volumes:
  postgres-data:
  settlewithcircles-redis-data:
