# Generated by Django 5.2.4 on 2025-07-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buddybill", "0002_buddygroup_buddygroupuser_topictag_transaction_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFriend",
        ),
    ]
